<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \ContactUs\Form\ContactUsForm $form
 * @var string $heading
 * @var string $html
 * @var string $message
 * @var string $status "success" or "error"
 * @var string $contact "us" or "author"
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$formText = $plugins->get('formText');
$formRow = $plugins->get('formRow');
$formEmail = $plugins->get('formEmail');
/** @var \Laminas\Form\View\Helper\FormLabel $formLabel */
$formLabel = $plugins->get('formLabel');
$formTextarea = $plugins->get('formTextarea');

$element = null;
?>

<?php if ($message): ?>
<p class="explanation <?= $status ?>"><?= $message ?></p>
<?php endif; ?>

<?php if (!$form) return;

    $form->get('name')
        ->setLabel('Prénom Nom')
        ->setAttribute('required', 'required')
        ->setLabelAttributes(['class' => 'required'])
        ->setAttribute('placeholder', 'Jean Dupont');
    $form->get('from')
        // ->setLabel('Mail' . ' <span class="required">*</span>')->setLabelOptions(['disable_html_escape' => true])
        ->setLabel('Courriel')
        ->setAttribute('placeholder', 'jean@dupont.fr');
    $form->get('message')
        ->setLabel('Posez votre question');
    $form->get('submit')
        ->setAttribute('class', 'form-button submit-button')
        ->setValue('Envoyer');
    $user = $this->identity();
?>

<?= $this->form()->openTag($form->setAttribute('class', 'limited-access-form')) ?>
    <?php if ($user): ?>
    <div>
        <p>
            <?= $escape(sprintf($translate('Message de %s (%s)'), $user->getName(), $user->getEmail())) ?>
        </p>
    </div>
    <?php else: ?>
    <div>
        <?= $formLabel($form->get('name')) ?>
        <?= $formText($form->get('name')) ?>
    </div>
    <div>
        <?= $formLabel($form->get('from')) ?>
        <?= $formEmail($form->get('from')) ?>
    </div>
    <?php endif ?>

    <?php $element = $form->get('message'); ?>
    <div>
        <?= $formLabel($element->setLabel('Posez votre question')); ?>
        <?= $formTextarea($element); ?>
    </div>
    <ul class="form-buttons">
        <li><button type="submit" class="form-button submit-button"><?= $escape($translate('Envoyer')) ?></a></li>
    </ul>
    <?php
    foreach ($form->getElements() as $element):
        if ($element instanceof \Laminas\Form\Element\Csrf || $element instanceof \Laminas\Form\Element\Hidden):
            echo $formRow($element);
        endif;
    endforeach;
    ?>
<?= $this->form()->closeTag() ?>
