<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $values
 * @var array $templateProperties If any.
 * Options:
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$themeSetting = $plugins->get('themeSetting');
$themeFunctions = $plugins->get('ThemeFunctions');

$labelInfo = $siteSetting('property_label_information');

$showLocale = (bool) $siteSetting('show_locale_label', true);
$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $plugins->get('lang')();
$langHtml = $filterLocale ? $lang : null;

$browseTerms = $themeSetting('resource_values_properties_browse', []);
/*
$browseTerms = [
    'dcterms:creator',
    'dcterms:subject',
//    'curation:tag',
    'curation:access',
    'bibo:degree',
];
*/
$notBrowseTerms = [
    'dcterms:title',
    'dcterms:abstract',
    'dcterms:tableOfContents',
    'dcterms:description',
    'extracttext:extracted_text',
    'bibo:content',
    'dcterms:identifier',
    'bibo:identifier',
    'bibo:uri',
    'dctems:available',
    'dcterms:date',
    'dcterms:created',
    'dcterms:dateAccepted',
    'dcterms:dateCopyrighted',
    'dcterms:dateSubmitted',
    'dcterms:issued',
    'dcterms:modified',
    'dcterms:valid',
    'curation:dateEnd',
    'curation:dateStart',
    'bibo:argued',
    // Plus de rebond pour les mots-clés.
    'curation:tag',
];

// TODO Déplacer cela dans le module via les événements.
if ($resource) {
    $values = $themeFunctions->danteAdvancedTemplateValues($resource->resourceTemplate(), $values);
}
?>

<?php foreach ($values as $term => $propertyData):
    if (isset($propertyData['term'])) $term = $propertyData['term'];
    ?>
    <li>
       <label>
            <?php if ($propertyData['alternate_label']): ?>
            <?= $escape(ucfirst($propertyData['alternate_label'])) ?>
            <?php else: ?>
            <?= $escape(ucfirst($translate($propertyData['property']->label()))) ?>
            <?php endif; ?>
            <?php if ('term' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </label>
        <ul>
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            // TODO A supprimer après réimport des données sans notice utilisateur.
            if ($term === 'dcterms:creator' && count($propertyData['values']) > 1 && strpos($value->value(), '@')) continue;
            $valueType = $value->type();
            $valueLang = $value->lang();
            $class = ['value'];
            $valueResource = $value->valueResource();
            if ($valueResource) {
                $class[] = 'resource';
                $class[] = $escape($valueResource->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <?php if (!$filterLocale || $valueLang == '' || strcasecmp($valueLang, $lang) == 0): ?>
                <li class="<?= implode(' ', $class) ?>" lang="<?= $escape($valueLang) ?>">
                    <?php if ($showLocale && $valueLang): ?>
                    <span class="language"><?= $valueLang ?></span>
                    <?php endif; ?>
                    <?php $val = $valueResource ? $valueResource->displayTitle() : $value->asHtml($langHtml) ?>
                    <?php // if ($term === 'dcterms:date' && preg_match('~\d\d\d\d~', $val)): ?>
                    <?php // echo substr($val, 0, 4) ?>
                    <?php // else: ?>
                    <?= $val ?>
                    <?php // endif ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
            </ul>
    </li>
<?php endforeach; ?>
