<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array|\AppendIterator $values
 * @var array $templateProperties
 *
 * Warning: this template is used by default by value-annotations.
 * In that case, only $values is available in version 4.0.
 * The same issue was fixed in #1634 and #1958.
 * @var \Omeka\Api\Representation\ValueAnnotationRepresentation|null $valueAnnotation
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$themeSetting = $plugins->get('themeSetting');
$themeFunctions = $plugins->get('ThemeFunctions');

$labelInfo = $siteSetting('property_label_information');

$showLocale = (bool) $siteSetting('show_locale_label', true);
$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $plugins->get('lang')();
$langHtml = $filterLocale ? $lang : null;

// TODO Déplacer cela dans le module via les événements.
if ($resource) {
    $values = $themeFunctions->advancedTemplateValues($resource->resourceTemplate(), $values);
}
?>

<?php foreach ($values as $term => $propertyData):
    if (isset($propertyData['term'])) $term = $propertyData['term'];
    ?>
    <li>
       <label>
            <?php if ($propertyData['alternate_label']): ?>
            <?= $escape(ucfirst($propertyData['alternate_label'])) ?>
            <?php else: ?>
            <?= $escape(ucfirst($translate($propertyData['property']->label()))) ?>
            <?php endif; ?>
            <?php if ('term' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </label>
        <ul data-property="<?= $term ?>">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            // TODO A supprimer après réimport des données sans notice utilisateur.
            if ($term === 'dcterms:creator' && count($propertyData['values']) > 1 && strpos($value->value(), '@')) continue;
            $valueType = $value->type();
            $valueLang = $value->lang();
            $class = ['value'];
            $valueResource = $value->valueResource();
            if ($valueResource) {
                $class[] = 'resource';
                $class[] = $escape($valueResource->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <?php if (!$filterLocale || $valueLang == '' || strcasecmp($valueLang, $lang) == 0): ?>
                <li class="<?= implode(' ', $class) ?>" lang="<?= $escape($valueLang) ?>">
                    <?php if ($showLocale && $valueLang): ?>
                    <span class="language"><?= $valueLang ?></span>
                    <?php endif; ?>
                    <?= $value->asHtml($langHtml) ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
            </ul>
    </li>
<?php endforeach; ?>
