<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Contribute\Form\ContributeForm $form
 * @var array $fields
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $mode "read" (for template) or "write"
 *
 * @var null $contribution
 * @var ?int $etape
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$themeFunctions = $plugins->get('ThemeFunctions');

$siteSlug = $site->slug();

$this->htmlElement('body')->appendAttribute('class', 'edit contribution ' . $this->params()->fromRoute('resource') . ' resource');

$steps = $themeFunctions->currentProcess('add', $contribution ?? null, $fields ?? null, $mode ?? 'write');
$this->vars()->offsetSet('steps', $steps);

$ariane = '<nav class="breadcrumbs content-with-margin">
    <ul>
        <li><a href="' . $url('site', ['site-slug' => $siteSlug]) . '">' . $escape($translate('Accueil')) . '</a></li>
        <li><a href="' . $url('site/contribution', ['resource' => 'contribution'], true) . '">' . $escape($translate('Nouveau dépôt')) . '</a></li>
<!--
        <li><span>' . $escape('Nouveau dépôt') . '</span></li>
-->
        <li><span>' . ($steps['stepNumber'] === 1 ? $escape($translate('Type de document')) : $escape($translate('Détails'))) . '</span></li>
    </ul>
</nav>';

$themeFunctions->appendVarsToView([
    'ariane' => $ariane,
    'mainClass' => 'depot-content depot-form-' . $steps['stepNumber'],
]);
?>

<?= $this->partial('contribute/site/contribution/aside')?>

<div class="container content etape-courante-<?= $steps['stepNumber'] ?>">
    <div class="messages">
        <p><?= $this->messages() ?></p>
    </div>
    <?php if (count($fields)):
    // The two lists of fields are merged in one form by default.
        $this->trigger('view.edit.before');
        echo $partial('contribute/site/contribution/form', [
            'site' => $site,
            'resource' => null,
            'contribution' => null,
            'form' => $form,
            'fields' => $fields,
            'fieldsByMedia' => $fieldsByMedia,
            'fieldsMediaBase' => $fieldsMediaBase,
            'action' => 'add',
            'mode' => $mode,
            'submitLabel' => $translate('Submit'),
            'isMainForm' => true,
            'skipContributeCss' => true,
            'steps' => $steps,
        ]);
        $this->trigger('view.edit.after');
    elseif ($form): // First step form to select a resource template.
        $escapeAttr = $plugins->get('escapeHtmlAttr');
        $formElement = $plugins->get('formElement');
        /**
         * @var \Laminas\Form\Element\Radio $template
         */
        $form->prepare();
        $template = $form->get('template')
            ->setAttribute('required', 'required')
            ->setLabel(' ');
        $templateId = $template->getValue();
        $this->vars()->offsetSet('stepPart', 'top');
        ?>
        <?= $partial('contribute/site/contribution/steps') ?>
    <?= $this->form()->openTag($form) ?>
        <h2 for="template"><?= $escape($translate('1. Type de document')) ?></h2>
        <fieldset class="form-content"<?= $mode === 'read' ? ' disabled="disabled"' : '' ?>>
            <ul class="form-radio-buttons">
                <?php foreach ($form->getTemplates() as $selectTemplateId => $selectTemplateLabel): ?>
                <li>
                    <label>
                        <input id="template" type="radio" name="template" value="<?= $escapeAttr($selectTemplateId) ?>" <?= $templateId ? 'readonly="readonly"' : 'required="required"' ?> <?= $selectTemplateId === $templateId ? 'checked="checked"' : '' ?>/>
                        <span><?= $escape($selectTemplateLabel) ?></span>
                    </label>
                </li>
                <?php endforeach; ?>
            </ul>
        </fieldset>
        <?= $formElement($form->get('step')) ?>
        <?= $formElement($form->get('next')) ?>
        <?= $formElement($form->get('mode')->setValue($mode)) ?>
        <?= $formElement($form->get('csrf')) ?>
        <?= $this->form()->closeTag() ?>
        <?php $this->vars()->offsetSet('stepPart', 'bottom'); ?>
        <?= $partial('contribute/site/contribution/steps') ?>
        <?php
    else: ?>
    <div class="messages">
        <p><?= $escape($translate('A template with fields is required to add a resource. Ask the administrator for more information.')) ?></p>
    </div>
    <?php endif; ?>
</div>
