<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Contribute\Form\ContributeForm $form
 * @var array $fields
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" or "write"
 * @var string $submitLabel
 * @var bool $isMainForm
 * @var bool $skipContributeCss
 * When called recursively for sub-fields (media):
 * @var ?int $indexMedia
 * @var array $fieldsMedia
 *
 * @var array $steps
 */

// See common/resource-values.

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$formElement = $plugins->get('formElement');
$themeFunctions = $plugins->get('ThemeFunctions');

$vars = $this->vars();
$labelInfo = $this->siteSetting('property_label_information') ?? $this->setting('property_label_information');

// Prepare variables one time for the form and all sub-forms.
if ($isMainForm) {
    // No echo: only includes css, js and variables.
    $partial('contribute/site/contribution/form-include');
    /**
     * @var \Laminas\View\Helper\Url $url
     * @var \Laminas\View\Helper\Partial $partial
     * @var \Laminas\View\Helper\EscapeHtml $escape
     * @var \Laminas\I18n\View\Helper\Translate $translate
     * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
     * @var \Omeka\Api\Manager $apiManager
     * @var ?array $customVocabBaseTypes
     * @var array $valueResourceTypes
     * @var array $valueResourceQueries
     * @var callable $shortResourceTitle
     * @var string $baseUrlFiles
     * @var string $mode "read" (for template) or "write"
     */
    $contributeVars = $plugins
        ->get(\Laminas\View\Helper\ViewModel::class)
        ->getRoot()
        ->getVariable('contributeVars') ?? [];
    extract($contributeVars);
    $vars = $this->setVars(new \Laminas\View\Variables($contributeVars))->vars();
    unset($contributeVars);
}

$disabled = $mode === 'read' ? ' disabled="disabled"' : '';
?>

<?php if ($isMainForm): ?>

<?php $vars->offsetSet('stepPart', 'top') ?>
<?= $partial('contribute/site/contribution/steps') ?>

<?php
// On ne se sert pas de ce bouton.
$form->get('submit')
    ->setAttribute('form', $form->getAttribute('id'))
    ->setAttribute('class', 'form-button save-button')
    ->setValue('Enregistrer'); // @translate
?>

<?= $this->form()->openTag($form) ?>
<fieldset class="etape-2"<?= $disabled ?>><?php // Afficher l'étape permet de la cacher via le css. ?>
    <h2><?= $escape($translate('2. Détails')) ?></h2>
    <?php // Le même en bas et dans la sous-forme pour les fichiers. ?>
    <ul id="page-actions" class="form-buttons">
        <?php if ($mode === 'read'): ?>
        <li><a href="<?= $contribution ? $contribution->url('edit') : '' ?>" class="form-button edit-button">Éditer</a></li>
        <?php else: ?>
        <?php if ($steps['step'] === 'fichiers'): ?>
        <li><a href="<?= $contribution ? $contribution->url('view') . '?next=fichiers' : '' ?>" class="form-button cancel-button"><?= $escape($translate('Annuler')) ?></a></li>
        <li><button class="form-button" type="submit" name="next" value="edit-fichiers" form="<?= $form->getAttribute('id') ?>"><span><?= $escape($translate('Valider')) ?></span></button></li>
        <?php else: ?>
        <li><a href="<?= $contribution ? $contribution->url('view') : '' ?>" class="form-button cancel-button"><?= $escape($translate('Annuler')) ?></a></li>
        <li><button class="form-button" type="submit" name="next" value="edit-notice" form="<?= $form->getAttribute('id') ?>"><span><?= $escape($translate('Enregistrer')) ?></span></button></li>
        <?php endif; ?>
        <?php endif; ?>
        <?php /*
        <?php if ($contributionResource = $contribution && $contribution->resource() ? $contribution->resource() : null): ?>
        <?= $hyperlink($translate('Go back to resource'), $url('site/resource-id', ['controller' => $contributionResource->getControllerName(), 'action' => 'show'], true), ['class' => 'btn btn-danger text-light', 'role' => 'button']) ?>
        <?php endif; ?>
        */ ?>
    </ul>
    <?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?php endif; ?>

    <?php // Display the special field for media file (required, not a property, and cannot be set in resource template). ?>
    <?php if (!$isMainForm):
        // Only one file is allowed by media and it cannot be updated, like in Omeka.
        $file = $fieldsMedia['file']['contributions'][0]['proposed']['store'] ?? null;
        ?>
        <?php if ($file): ?>
    <div class="property form-content" data-term="file">
        <p><?= $escape($translate('Fichier déjà téléchargé')) ?></p>
        <div>
            <label><a href="<?= $escapeAttr($baseUrlFiles . '/contribution/' . $file) ?>" download="download"><?= $escape($fieldsMedia['file']['contributions'][0]['proposed']['@value']) ?></a></label>
            <input type="hidden"  name="media[<?= $indexMedia ?>][file][0][store]" value="<?= $escapeAttr($file) ?>"/>
            <input type="hidden"  name="media[<?= $indexMedia ?>][file][0][@value]" value="<?= $escapeAttr($fieldsMedia['file']['contributions'][0]['proposed']['@value']) ?>"/>
        </div>
        <?php else: ?>
        <p><?= $escape($translate('Télécharger le document depuis votre ordinateur')) ?></p>
        <label class="file-upload-button">
            <input type="file" class="form-control input-value" data-value-key="@value" name="media[<?= $indexMedia ?>][file][0][@value]" required="required"/>
            <?= $escape($translate('Télécharger')) ?>
        </label>
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php // Display the edited resource, with edited or non-edited fields, plus the non-editable original fields. ?>

    <?php foreach ($isMainForm ? $fields : $fieldsMedia as $term => $field):
        if ($term === 'file') continue;
        // Don't display empty values that are not fillable.
        if (empty($field['contributions']) && !$field['fillable']) continue;
        $indexFieldInput = 0;
        /**
         * @var \AdvancedResourceTemplate\Api\Representation\ResourceTemplatePropertyDataRepresentation $templateProperty
         * @var \Omeka\Api\Representation\PropertyRepresentation $property
         */
        $templateProperty = $field['template_property'];
        $property = $field['property'];
        $multilang = $themeFunctions->templatePropertyThemeOption($templateProperty, 'multilang');
        $maxValues = $field['max_values'] ?? 0;
        $vars->offsetSet('field', $field);
        $vars->offsetSet('term', $term);
        $vars->offsetSet('property', $property);
        $vars->offsetSet('indexFieldInput', $indexFieldInput);
        $vars->offsetSet('templateProperty', $templateProperty);
        ?>

    <div class="property form-content<?= $multilang || !$maxValues || $maxValues > 1 ? ' multivalues' : '' ?>" data-term="<?= $term ?>">
        <?php if (!$multilang): // Dans ce thème, le libellé multingue est affiché avec le champ. ?>
        <?php // Display property label. ?>
        <label<?= empty($field['required']) ? '' : ' class="required"' ?>>
            <?= isset($field['alternate_label']) ? $escape($field['alternate_label']) : $escape($translate($property->label())) ?>
            <?php if (!isset($field['property'])):?>
            <?php // Nothing to do (file). ?>
            <?php elseif ($labelInfo === 'term'): ?>
            <span class="field-term">(<?= $escape($field['property']->term()) ?>)</span>
            <?php elseif ($labelInfo === 'vocab'): ?>
            <span class="field-term">(<?= $escape($field['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </label>
        <?php endif; ?>

        <?php // Simple display of the value for properties that are not editable or without datatypes. ?>

        <?php if (!$field['editable'] && !$field['fillable'] || !count($field['datatypes'])): ?>
        <ul class="values">
            <?php
            foreach ($field['values'] as $value):
                $vars->offsetSet('value', $value);
                echo $partial('contribute/site/contribution/form-value');
            endforeach; ?>
        </ul>
        <?php // Early end this property and continue to next fields. ?>
    <?= '</div>' ?>
            <?php continue;
            endif; ?>

        <?php // Editable fields, that may have been edited or not. ?>
        <?php // Some contributions may be empty (minimum number of values, or a required one). ?>

        <ul class="values">
            <?php

            // Gère l'option spécifique `multilang` (label différent selon la langue).
            if ($multilang) {
                $valueType = reset($field['datatypes']);
                $mapIdxs = array_keys($field['contributions']);
                $idx = 0;
                foreach ($multilang as $lang => $langLabel) {
                    $pointer = $mapIdxs[$idx] ?? $idx;
                    if (!isset($mapIdxs[$idx])) {
                        $field['contributions'][$pointer] = ['type' => $valueType, 'required' => $field['required'], 'original' => ['value' => null, '@value' => null], 'proposed' => ['@value' => null], 'template_property' => null];
                    }
                    $field['contributions'][$pointer]['@language'] = $lang;
                    $field['contributions'][$pointer]['langLabel'] = $langLabel;
                    ++$idx;
                    if ($maxValues && $idx >= $maxValues) break;
                }
            }

            foreach ($field['contributions'] as $indexContribution => $fieldContribution):
                /** @var \Omeka\Api\Representation\ValueRepresentation $value */
                $value = $fieldContribution['original']['value'];
                if (!$value && !$field['fillable']) continue;
                $typeColon = strtok((string) $fieldContribution['type'], ':');
                $vars->offsetSet('indexContribution', $indexContribution);
                $vars->offsetSet('fieldContribution', $fieldContribution);
                $vars->offsetSet('value', $value);
                // Check if the value exists or is editable (the value may be empty).
                if ($value && !$field['editable']):
                    echo $partial('contribute/site/contribution/form-value');
                else:
                    switch ($fieldContribution['type']):
                        case 'literal':
                            echo $partial('contribute/site/contribution/form-input-literal');
                            break;
                        case 'resource':
                        case 'resource:item':
                        case 'resource:media':
                        case 'resource:itemset':
                            echo $partial('contribute/site/contribution/form-input-resource');
                            break;
                        case 'uri':
                            echo $partial('contribute/site/contribution/form-input-uri');
                            break;
                        case 'numeric:integer':
                            echo $partial('contribute/site/contribution/form-input-numeric-integer');
                            break;
                        case 'numeric:timestamp':
                            echo $partial('contribute/site/contribution/form-input-numeric-timestamp');
                            break;
                        case $typeColon === 'customvocab':
                            echo $partial('contribute/site/contribution/form-input-custom-vocab');
                            break;
                        case $typeColon === 'valuesuggest' || $typeColon === 'valuesuggestall':
                            echo $partial('contribute/site/contribution/form-input-value-suggest');
                            break;
                        default:
                            // Other datatypes are not yet editable.
                            if ($value):
                                echo $partial('contribute/site/contribution/form-value');
                            endif;
                            break;
                    endswitch;
                endif;
                ++$indexFieldInput;
                $vars->offsetSet('indexFieldInput', $indexFieldInput);
            endforeach;
            ?>
        </ul>

        <?php // Add a button to add a new value for fillable properties. ?>
        <?php // The button is always added to manage value removing. ?>
        <?= $partial('contribute/site/contribution/form-value-more') ?>

    </div>
    <?php endforeach; // Next field/property. ?>

<?php if ($isMainForm): ?>
</fieldset>

    <?php if (count($fieldsMediaBase)): ?>
<fieldset class="contribute-medias etape-3" data-next-index-media="<?= count($fieldsByMedia) ?>"<?= $disabled ?>>
    <?php // For end user, "media" means "files". ?>
    <h2><?= $escape($translate('3. Téléchargement')) ?></h2>
    <ul class="actions form-buttons">
        <?php if ($mode === 'read'): ?>
        <li><a href="<?= $contribution ? $contribution->url('edit') : '' ?>?next=fichiers" class="form-button edit-button">Éditer</a></li>
        <?php else: ?>
        <li><button class="form-button" type="submit" name="next" value="edit-fichiers" form="<?= $form->getAttribute('id') ?>"><span><?= $escape($translate('Valider')) ?></span></button></li>
        <?php endif; ?>
    </ul>
    <div class="sub-forms">
            <?php
            $vars->offsetSet('isMainForm', false);
            $indexMedia = 0;
            foreach ($fieldsByMedia as $fieldsMedia): ?>
        <div class="contribute-media sub-form form-content document-parts-forms" name="media[<?= $indexMedia ?>]" data-index-media="<?= $indexMedia ?>">
            <div class="document-part-template document-part-fields">
                <?php
                $vars->offsetSet('indexMedia', $indexMedia);
                $vars->offsetSet('fieldsMedia', $fieldsMedia);
                ?>
                <?= $partial('contribute/site/contribution/form') ?>
                <?php if ($mode !== 'read'): ?>
                <ul class="actions form-buttons">
                    <li><button type="button" class="remove-media button o-icon-delete form-button"><?= $escape($translate('Remove file')) ?></button></li>
                </ul>
                <?php endif; ?>
            </div>
        </div>
            <?php ++$indexMedia; ?>
            <?php endforeach; ?>
    </div>
    <div class="inputs inputs-media form-content">
        <button type="button" class="add-media-new button o-icon-add add-document-to-depot-btn">
            <span><?= $translate('Ajouter un fichier') ?></span>
        </button>
    </div>
</fieldset>
    <?php
    $indexMedia = null;
    $fieldsMedia = [];
    $vars->offsetSet('isMainForm', true);
    $vars->offsetSet('indexMedia', $indexMedia);
    $vars->offsetSet('fieldsMedia', $fieldsMedia);
    ?>
    <?php endif; ?>

    <?= $formElement($form->get('template')) ?>
    <?= $action === 'add' ? $formElement($form->get('step')) : '' ?>
    <?php // Voir steps pour next. ?>
    <?= $formElement($form->get('mode')) ?>
    <?= $formElement($form->get('csrf')) ?>

    <?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

    <?= $this->form()->closeTag() ?>

    <?php $vars->offsetSet('stepPart', 'bottom') ?>
    <?= $partial('contribute/site/contribution/steps') ?>

    <?php // Le même en haut. ?>
    <ul id="page-actions" class="form-buttons">
        <?php if ($mode === 'read'): ?>
        <li><a href="<?= $contribution ? $contribution->url('edit') . ($steps['step'] === 'fichiers' ? '?next=fichiers' : '') : '' ?>" class="form-button edit-button">Éditer</a></li>
        <?php else: ?>
        <?php if ($steps['step'] === 'fichiers'): ?>
        <li><a href="<?= $contribution ? $contribution->url('view') . '?next=fichiers' : '' ?>" class="form-button cancel-button"><?= $escape($translate('Annuler')) ?></a></li>
        <li><button class="form-button" type="submit" name="next" value="edit-fichiers" form="<?= $form->getAttribute('id') ?>"><span><?= $escape($translate('Valider')) ?></span></button></li>
        <?php else: ?>
        <li><a href="<?= $contribution ? $contribution->url('view') : '' ?>" class="form-button cancel-button"><?= $escape($translate('Annuler')) ?></a></li>
        <li><button class="form-button" type="submit" name="next" value="edit-notice" form="<?= $form->getAttribute('id') ?>"><span><?= $escape($translate('Enregistrer')) ?></span></button></li>
        <?php endif; ?>
        <?php endif; ?>
        <?php /*
        <?php if ($contributionResource = $contribution && $contribution->resource() ? $contribution->resource() : null): ?>
        <?= $hyperlink($translate('Go back to resource'), $url('site/resource-id', ['controller' => $contributionResource->getControllerName(), 'action' => 'show'], true), ['class' => 'btn btn-danger text-light', 'role' => 'button']) ?>
        <?php endif; ?>
        */ ?>
    </ul>

    <?php //= $partial('common/resource-form-templates') ?>
    <?= $partial('contribute/site/contribution/form-inputs-default') ?>

    <?php if (count($fieldsMediaBase)): ?>
    <div id="edit_template_media" class="contribute_template media" style="display:none;">
        <div class="contribute-media sub-form form-content document-parts-forms" name="media[]" data-index-media="">
            <div class="document-part-template document-part-fields">
                <?php
                $vars->offsetSet('isMainForm', false);
                $vars->offsetSet('indexMedia', null);
                $vars->offsetSet('fieldsMedia', $fieldsMediaBase);
                ?>
                <?= $partial('contribute/site/contribution/form') ?>
                <?php
                $vars->offsetSet('isMainForm', true);
                $vars->offsetSet('indexMedia', null);
                $vars->offsetSet('fieldsMedia', null);
                ?>
                <ul class="actions form-buttons">
                    <li><button type="button" class="remove-media button o-icon-delete form-button"><?= $escape($translate('Remove file')) ?></button></li>
                </ul>
            </div>
        </div>
    </div>
    <?php endif; ?>

</div>

<?php endif; ?>
