<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var ?\Contribute\Api\Representation\ContributionRepresentation $resource
 * @var ?\Contribute\Api\Representation\ContributionRepresentation $contribution
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Entity\User $user
 * @var array $fields
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 */

include OMEKA_PATH . '/modules/Contribute/view/contribute/site/contribution/form.phtml';
