<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\LoginForm $form
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$themeFunctions = $plugins->get('ThemeFunctions');

$siteSlug = $site->slug();

$this->htmlElement('body')->appendAttribute('class', 'guest login');

$ariane = '<nav class="breadcrumbs content-with-margin">
    <ul>
        <li><a href="' . $url('site', ['site-slug' => $siteSlug]) . '">' . $escape($translate('Accueil')) . '</a></li>
        <li><span>' . $escape($translate('Mon compte')) . '</span></li>
    </ul>
</nav>';

$themeFunctions->appendVarsToRootView([
    'ariane' => $ariane,
    'mainClass' => 'user-account user-infos',
]);

?>

<div class="content">

    <?= $this->pageTitle($this->siteSetting('guest_login_text') ?: ($this->setting('guest_login_text') ?: $translate('Login'))) ?>

    <?php if (class_exists('ShibbolethModule', false)): // Support de Shibboleth: utilise la redirection admin pour éviter une boucle. ?>
    <div class="page-block">
        <p class="forgot-password">
            <a href="<?= $url('admin') ?>">Se connecter via Shibboleth</a>
        </p>
    </div>
    <?php endif; ?>

    <div class="page-block">
        <?php if (empty($form)): ?>
        <p>
            <?= $translate('Your account seems to have an error. Contact your administrator to login.') ?>
        </p>
        <?php else: ?>
        <?= $this->form($form) ?>
        <?php endif; ?>

        <p class="forgot-password">
            <?= $this->hyperlink($translate('Forgot password?'), $url('site/guest/anonymous', ['action' => 'forgot-password'], true)) ?>
        </p>

        <?php $this->trigger('view.login.after'); ?>
    </div>

</div>
