<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\LoginForm $form
 */

// Dans le site, il n'est pas possible d'avoir un compte spécifique et tous les utilisateurs sont authentifiés par Shibboleth.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$themeFunctions = $plugins->get('ThemeFunctions');

$siteSlug = $site->slug();

$this->htmlElement('body')->appendAttribute('class', 'guest login');

$ariane = '<nav class="breadcrumbs content-with-margin">
    <ul>
        <li><a href="' . $url('site', ['site-slug' => $siteSlug]) . '">' . $escape($translate('Accueil')) . '</a></li>
        <li><span>' . $escape($translate('Mon compte')) . '</span></li>
    </ul>
</nav>';

$themeFunctions->appendVarsToView([
    'ariane' => $ariane,
    'mainClass' => 'user-account user-infos',
]);

?>

<div class="content">

    <?= $this->pageTitle($this->siteSetting('guest_login_text') ?: ($this->setting('guest_login_text') ?: $translate('Login'))) ?>

    <div class="page-block">
        <?php if (empty($form)): ?>
        <p>
            <?= $translate('Your account seems to have an error. Contact your administrator to login.') ?>
        </p>
        <?php else: ?>
        <?= $this->form($form) ?>
        <?php endif; ?>

        <p class="forgot-password">
            <?= $this->hyperlink($translate('Forgot password?'), $this->url('site/guest/anonymous', ['action' => 'forgot-password'], true)) ?>
        </p>

        <?php $this->trigger('view.login.after'); ?>
    </div>

</div>
