<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 */

// Attention : les médias ne fonctionnent qu'avec les fichiers et il n'y a pas de visionneuse.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$themeSetting = $plugins->get('themeSetting');
$themeFunctions = $plugins->get('ThemeFunctions');

$contactUs = $plugins->has('contactUs') ? $plugins->get('contactUs') : null;

$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$embedMedia = $siteSetting('item_media_embed', false);
$medias = $themeFunctions->mediaItem($item);

$filterLocale = (bool) $siteSetting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;
$langValue = $filterLocale ? [$siteLang, ''] : null;
$siteSlug = $site->slug();

$searchingUrl = $plugins->has('searchingUrl') ? $plugins->get('searchingUrl')() : $url('site/resource', ['site-slug' => $siteSlug]);

$resourceUrl = $resource->siteUrl($siteSlug);

$resourceClass = $resource->resourceClass();
$resourceClassTerm = $resourceClass ? $resourceClass->term() : null;
$isThese = $resourceClassTerm === 'bibo:Thesis';
// $isTravailEtudiant = !$isThese;

$documentType = $themeFunctions->documentType($resource);

$accessLevel = $themeFunctions->accessLevel($resource);
$accessLabel = $themeFunctions->accessLabel($accessLevel);
$citation = $themeFunctions->citation($resource);

$resourceTitle = $resource->displayTitle(null, $lang);
$itemSets = $item->itemSets();

$ariane = '<nav class="breadcrumbs content-with-margin">
    <ul>
        <li><a href="' . $url('site', ['site-slug' => $siteSlug]) . '">' . $escape($translate('Accueil')) . '</a></li>
        <li><a href="' . $searchingUrl . '">' . $escape($translate('Recherche')) . '</a></li>
        <li><span>' . $escape($resourceTitle) . '</span></li>
    </ul>
</nav>';

$themeFunctions->appendVarsToRootView([
    'resource' => $resource,
    'ariane' => $ariane,
    'mainClass' => 'item-content',
]);
?>

<div class="content">

    <?php $this->trigger('view.show.before'); ?>

    <div class="item-content-header">
        <?= $this->pageTitle($resourceTitle, 1) ?>
        <ul class="authors-and-date"><?= sprintf('%s (%s)', $themeFunctions->formatAuthor($resource), $themeFunctions->year($resource)) ?></ul>
        <div class="document-type-and-access">
            <div class="document-type"><?= $escape($translate($documentType)) ?></div>
            <div class="document-access access-<?= $accessLevel ?>"><?= $accessLabel ?></div>
        </div>
    </div>

    <div class="resource-metadata-and-document-parts">
        <ul class="resource-metadata">
            <?= $resource->displayValues(['resource' => $resource]) ?>
            <?php if (count($itemSets)): ?>
            <li>
                <label><?= $translate('Item sets') ?></label>
                <ul>
                    <?php foreach ($itemSets as $itemSet): ?>
                    <li><a href="<?= $escapeAttr($itemSet->url()); ?>"><?= $itemSet->displayTitle(null, $lang); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php endif; ?>
            <?php if ($siteSetting('show_attached_pages', true) && ($sitePages = $item->sitePages($site->id()))): ?>
            <li>
                <label><?php echo $translate('Site pages'); ?></label>
                <ul>
                    <?php foreach ($sitePages as $sitePage): ?>
                    <li><?= $sitePage->link($sitePage->title()); ?></li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php endif; ?>
            <?php /*
            $subjectValues = $item->displaySubjectValues([
                'page' => (int) $this->params()->fromQuery('page', 1),
                'perPage' => 25,
                'resourceProperty' => $this->params()->fromQuery('resource_property'),
            ]);
            ?>
            <?php if ($subjectValues): ?>
            <li>
                <label><?= $translate('Linked resources') ?></label>
                <?= $subjectValues ?>
            </li>
            <?php endif; ?>
            */ ?>
        </ul>
        <aside class="aside-document-parts">
            <div class="aside-content">
                <?php if (!count($medias)): ?>
                <ul class="media-list">
                    <li class="document-parts">
                        <p><?= $translate('Pas de fichier disponible') ?></p>
                    </li>
                </ul>
                <?php else: ?>
                <ul class="media-list">
                    <?php foreach ($medias as $media):
                        /** @var \Omeka\Api\Representation\MediaRepresentation $mediaRes */
                        $mediaRes = $media['resource'];
                        if ($mediaRes) {
                            $title = $mediaRes->displayTitle();
                            $accessLevelMedia = $themeFunctions->accessLevel($mediaRes);
                            $accessLabelMedia = $themeFunctions->accessLabel($accessLevelMedia);
                            $originalUrl = $mediaRes->originalUrl();
                            // Attention : en cas d'accès restreint, le message est différent selon les documents et selon l'embargo.
                            // Pour les travaux étudiants = accès restreint UT2
                            // Pour les thèses = accès restreint communauté universitaire
                            // Si embargo, ajouter : jusqu'au JJ/MM/AAAA
                            if ($accessLevelMedia === 'reserved') {
                                $accessLabelMedia = $isThese ? 'Accès restreint communauté universitaire' : 'Accès restreint UT2J';
                            }
                            if ($accessLevelMedia !== 'free') {
                                $embargo = $mediaRes->value('curation:end');
                                if ($embargo) {
                                    $date = DateTime::createFromFormat('Y-m-d', $embargo->value());
                                    if (!$date) {
                                        $this->logger()->err('Date incorrecte dans curation:end du media #' . $mediaRes->id());
                                    }
                                    $accessLabelMedia .= ' jusqu’au ' . ($date ? $date->format('d-m-Y') : $embargo->value());
                                }
                            }
                        } else {
                            $title = $media['o:title'];
                            $accessLevelMedia = 'forbidden';
                            $accessLabelMedia = $translate('Non consultable');
                            $embargo = null;
                        }
                    ?>
                    <li class="document-parts">
                        <span class="document-part-name"><?= $title ?></span>
                        <?php if ($isThese): ?>
                        <div class="document-part-name document-version">Version : <span class="dante-version"><?= $escape($media['dante:version'] ?: '[indéfini]') ?></span></div>
                        <?php endif; ?>
                        <div class="document-access access-<?= $accessLevelMedia ?>"><?= $accessLabelMedia ?></div>
                        <div class="document-edition">

                            <?php if ($accessLevelMedia === 'free'
                                || ($mediaRes && $themeFunctions->accessMedia($mediaRes))
                            ): ?>

                            <ul class="form-buttons">
                                <?php if ($originalUrl): ?>
                                <li><a href="<?= $originalUrl ?>" class="form-button preview-button"><?= $translate('Visualiser') ?></a></li>
                                <li><a href="<?= $originalUrl ?>" class="form-button download-button" download="download"><?= $translate('Télécharger') ?></a></li>
                                <?php else: ?>
                                <li><a href="" class="form-button ask-copy-button"><?= $translate('Fichier manquant : demander une copie') ?></a></li>
                                <?php endif; ?>
                            </ul>

                            <?php elseif ($accessLevelMedia === 'reserved'): ?>

                            <ul class="form-buttons">
                                <li><a href="" class="form-button ask-copy-button"><?= $translate('Demander une copie') ?></a></li>
                            </ul>

                            <?php elseif ($accessLevelMedia === 'forbidden'): ?>

                            <ul class="form-buttons">
                                <li><a href="" class="form-button ask-copy-button"><?= $translate('Demander une copie') ?></a></li>
                            </ul>

                            <?php endif; ?>

                        </div>
                    </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
        </aside>
    </div>

    <div class="item-reference">
        <h3><?= $translate('Citation bibliographique') ?></h3>
        <p><?= $citation ?></p>
    </div>

    <?php $this->trigger('view.show.after'); ?>

</div>
