<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageRepresentation $page
 * @var string $pageBodyClass "page" and "site-page-" + page slug
 * @var bool $displayNavigation Always true when called directly
 * @var \Laminas\View\Helper\ViewModel $view
 */

// Gère le cas particulier des blocs "aside" et ajoute la classe "mainClass" si présente.

$plugins = $this->getHelperPluginManager();
$blockLayout = $plugins->get('blockLayout');
$themeFunctions = $plugins->get('ThemeFunctions');

/** @var \BlockPlus\View\Helper\BlockMetadata $blockMetadata */
$blockMetadata = $plugins->has('blockMetadata') ? $plugins->get('blockMetadata') : null;

$main = '';
$asides = '';
$countAsides = 0;
$hasMainClass = false;

$layouts = [];
foreach ($page->blocks() as $block) {
    $layout = $block->layout();
    if (!array_key_exists($layout, $layouts)) {
        // Prepare render only once per layout type.
        $layouts[$layout] = null;
        $blockLayout->prepareRender($layout);
    }
    if (
        ($layout === 'html' && strpos((string) $block->dataValue('template'), 'aside'))
        || ($layout === 'block' && strpos((string) $block->dataValue('template'), 'aside'))
    ) {
        $asides .= $blockLayout->render($block);
        ++$countAsides;
    } elseif ($layout === 'pageMetadata') {
        if ($blockMetadata && $mainClass = $blockMetadata('mainClass', $block)) {
            $themeFunctions->appendVarToRootView('mainClass', $mainClass);
        }
    } else {
        $main .= $blockLayout->render($block);
    }
}

if (!$hasMainClass) {
    $themeFunctions->appendVarToRootView('mainClass', $asides ? 'aside-page' : 'simple-page');
}

if ($countAsides > 1): ?>
<div class="asides">
    <?= $asides ?>
</div>

<?php else: ?>
    <?= $asides ?>
<?php endif; ?>

<div class="content">
    <?= $themeFunctions->sommaireIds($main) ?>
</div>
