<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $html
 * @var string $divclass
 * @var string $heading
 */

?>
<?php if (empty($divclass)): ?>

<div class="page-block block-html">
    <?php if (!empty($heading)): ?>
    <h2><?= $this->escapeHtml($heading) ?></h2>
    <?php endif; ?>
    <?= $html ?>
</div>

<?php else: ?>

<div class="page-block block-html <?= $this->escapeHtmlAttr($divclass) ?>">
    <?php if (!empty($heading)): ?>
    <h2><?= $this->escapeHtml($heading) ?></h2>
    <?php endif; ?>
    <?= $html ?>
</div>

<?php endif; ?>
