<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

$ufrOuComposante = 31925;

if (!isset($response) || empty($searchConfig->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchConfig->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');
$labelSubmit = $displaySubmit ? $searchConfig->subSetting('facet', 'label_submit', $translate('Apply facets')) : null;
$labelReset = $displayReset ? $searchConfig->subSetting('facet', 'label_reset', $translate('Reset facets')) : null;

$facetActives = $plugins->get('facetActives');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');
$facetSelectRange = $plugins->get('facetSelectRange');
$facetElementsTree = $isFacetModeButton ? $plugins->get('facetCheckboxesTree') : $plugins->get('facetLinksTree');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchConfig->setting('facet', []);
?>

<aside class="search-facets">
    <form id="form-facets" class="resources-list-filters-and-toggle toggle-parent">
        <a class="resources-list-close-filters" href=""></a>

        <a class="resources-list-toggle-filters" href=""><?= $translate('Filtres') ?></a>

        <?php if ($displayActive && count($activeFacets)): ?>
        <?= $facetActives(null, $activeFacets, $options) ?>
        <?php endif; ?>

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php $r = $displayReset === 'above' || $displayReset === 'both'; ?>
        <?php $s = ($displayFacetButton && ($displaySubmit === 'above' || $displaySubmit === 'both')); ?>
        <?php if ($r || $s): ?>
        <div class="apply-facets apply-facets-top form-buttons">
            <?php if ($s): ?>
            <button id="apply-facets" type="submit" class="form-button filter-button"><?= $labelSubmit ?></button>
            <?php endif ?>
            <?php if ($r): ?>
            <button id="reset-facets" type="reset" class="form-button reset-button"><?= $labelReset ?></button>
            <?php endif ?>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <ul class="search-facets-list resources-filters"><li><?= $translate('Pas de filtre.') ?></li></ul>
        <?php else: ?>
        <ul class="search-facets-list resources-filters">
            <?php foreach ($facets as $name => $facetValues): ?>
            <?php $facetType = empty($options['facets'][$name]['type']) ? 'Checkbox' : $options['facets'][$name]['type']; ?>
            <li class="search-facet toggle-parent opened">
                <a class="toggle" href="#"><?= $translate($facetLabel($name)) ?></a>
<?php
if (stripos($name, 'ufrOuComposante') !== false) {
    // Conserve la présentation des ufr à 2 niveaux pour les composantes.
    // Ne fonctionne que pour deux niveaux (Ufr ou composante).
    // Attention : il y a le cas du département des langues qui a un 3e niveau
    /** @var \Thesaurus\View\Helper\Thesaurus $thesaurus */
    $thesaurus = $plugins->get('thesaurus')($ufrOuComposante);
    $counts = array_column($facetValues, 'count', 'value');
    $facetValues = [];
    $flatTree = $thesaurus->flatTree();
    foreach ($flatTree as $data) {
        // Mettre tous les vraies facettes avec des résultats.
        if (isset($counts[$data['self']['title']])) {
            $facetValues[] = [
                'value' => $data['self']['title'],
                'count' => $counts[$data['self']['title']],
                'is' => true,
            ];
        }
        // Mettre les titres qui ont des enfants et au moins une facette réelle.
        elseif ($data['level'] === 0 && $data['self']['children']) {
            foreach ($data['self']['children'] as $childId) {
                if (isset($counts[$flatTree[$childId]['self']['title']])) {
                    $facetValues[] = [
                        'value' => $data['self']['title'],
                        'count' => 0,
                        'is' => false,
                    ];
                    break;
                }
            }
        }
        // Gère le 3e niveau.
        elseif ($data['level'] === 1 && $data['self']['children']) {
            foreach ($data['self']['children'] as $childId) {
                if (isset($counts[$flatTree[$childId]['self']['title']])) {
                    $facetValues[] = [
                        'value' => $data['self']['title'],
                        'count' => 0,
                        'is' => false,
                    ];
                    break;
                }
            }
        }
    }
} elseif (stripos($name, 'Date') !== false) {
    $counts = array_column($facetValues, 'count', 'value');
    krsort($counts);
    $facetValues = [];
    foreach ($counts as $key => $value) {
        $facetValues[] = [
            'value' => $key,
            'count' => $value,
        ];
    }
}
?>
                <?php if ($facetType === 'Select'): ?>
                <?= $facetSelect($name, $facetValues, $options) ?>
                <?php elseif ($facetType === 'SelectRange'): ?>
                <?= $facetSelectRange($name, $facetValues, $options) ?>
                <?php elseif ($facetType === 'Tree' || $facetType === 'Thesaurus'): ?>
                <?= $facetElementsTree($name, $facetValues, $options) ?>
                <?php else: ?>
                <?= $facetElements($name, $facetValues, $options) ?>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php $r = $displayReset === 'below' || $displayReset === 'both'; ?>
        <?php $s = ($displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both')); ?>
        <?php if ($r || $s): ?>
        <div class="apply-facets apply-facets-bottom form-buttons">
            <?php if ($s): ?>
            <button id="apply-facets" type="submit" class="form-button filter-button"><?= $labelSubmit ?></button>
            <?php endif ?>
            <?php if ($r): ?>
            <button id="reset-facets" type="reset" class="form-button reset-button"><?= $labelReset ?></button>
            <?php endif ?>
        </div>
        <?php endif; ?>

    </form>

</aside>
