<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

$ufrOuComposante = 31925;

if (!isset($response) || empty($searchConfig->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchConfig->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchConfig->setting('facet') ?? [];

// Affichage du sélecteur ufr/composante en l'absence de recherche.
// $noQuery = $query && !$query->getQuery() && !$query->getFilters() && !$query->getFilterQueries() && !$query->getDateRangeFilters();

?>

<aside class="search-facets">
    <form id="form-facets" class="resources-list-filters-and-toggle toggle-parent">
        <a class="resources-list-close-filters" href=""></a>

        <a class="resources-list-toggle-filters" href=""><?= $translate('Filtres') ?></a>

        <?php if ($displayActive && count($activeFacets)): ?>
        <ul class="search-facets-active resources-list-selected-filters">
            <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetValue): ?>
            <li><?= $facetActive($name, ['value' => $facetValue, 'count' => null], $options) ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
        <ul class="apply-facets apply-facets-top form-buttons">
            <li><button type="submit" class="form-button filter-button"><?= $translate('Filtrer') ?></button></li>
        </ul>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <ul class="search-facets-list resources-filters"><li><?= $translate('Pas de filtre.') ?></li></ul>
        <?php else: ?>
        <ul class="search-facets-list resources-filters">
            <?php foreach ($facets as $name => $facetValues): ?>
            <li class="search-facet toggle-parent opened">
                <a class="toggle" href="#"><?= $translate($facetLabel($name)) ?></a>
<?php
if (stripos($name, 'ufrOuComposante') !== false) {
    // Conserve la présentation des ufr à 2 niveaux pour les composantes.
    // Ne fonctionne que pour deux niveaux (Ufr ou composante).
    // Attention : il y a le cas du département des langues qui a un 3e niveau
    /** @var \Thesaurus\View\Helper\Thesaurus $thesaurus */
    $thesaurus = $plugins->get('thesaurus')($ufrOuComposante);
    $counts = array_column($facetValues, 'count', 'value');
    $facetValues = [];
    $flatTree = $thesaurus->flatTree();
    foreach ($flatTree as $data) {
        // Mettre tous les vraies facettes avec des résultats.
        if (isset($counts[$data['self']['title']])) {
            $facetValues[] = [
                'value' => $data['self']['title'],
                'count' => $counts[$data['self']['title']],
                'is' => true,
            ];
        }
        // Mettre les titres qui ont des enfants et au moins une facette réelle.
        elseif ($data['level'] === 0 && $data['self']['children']) {
            foreach ($data['self']['children'] as $childId) {
                if (isset($counts[$flatTree[$childId]['self']['title']])) {
                    $facetValues[] = [
                        'value' => $data['self']['title'],
                        'count' => 0,
                        'is' => false,
                    ];
                    break;
                }
            }
        }
        // Gère le 3e niveau.
        elseif ($data['level'] === 1 && $data['self']['children']) {
            foreach ($data['self']['children'] as $childId) {
                if (isset($counts[$flatTree[$childId]['self']['title']])) {
                    $facetValues[] = [
                        'value' => $data['self']['title'],
                        'count' => 0,
                        'is' => false,
                    ];
                    break;
                }
            }
        }
    }
} elseif (stripos($name, 'Date') !== false) {
    $counts = array_column($facetValues, 'count', 'value');
    krsort($counts);
    $facetValues = [];
    foreach ($counts as $key => $value) {
        $facetValues[] = [
            'value' => $key,
            'count' => $value,
        ];
    }
}
?>
                <?php if (($options['facets'][$name]['type'] ?? 'Checkbox') === 'Select'): ?>
                <?= $facetSelect($name, $facetValues, $options) ?>
                <?php else: ?>
                <?= $facetElements($name, $facetValues, $options) ?>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
        <ul class="apply-facets apply-facets-bottom form-buttons">
            <li><button type="submit" class="form-button filter-button"><?= $translate('Filtrer') ?></button></li>
        </ul>
        <?php endif; ?>

    </form>

</aside>
