<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 */

// Add headers (css or scripts) to be included for the form.
// The form itself is managed by search-form-main.

// The form can be used independantly of the search page, but they share the same css/js.

// Remove code to avoid to load the same files multiple times in your theme.


// Vide : Tous les liens sont mis dans layout.
