<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * For block layout:
 * @var string $heading Unused in current template.
 * @var bool $skipFormAction Remove action of the form, so it uses current page.
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$api = $plugins->get('api');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$translatePlural = $plugins->get('translatePlural');
$themeFunctions = $plugins->get('ThemeFunctions');

$vars = $this->vars();

// Used in case of a redirect of item-set/show to search, when used like item/browse.
$itemSetId = $this->params()->fromRoute('item-set-id');
// TODO Use site item set ?
/** @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet */
$itemSet = $itemSetId ? $api->searchOne('item_sets', ['id' => $itemSetId])->getContent() : null;

$skipFormAction = !empty($skipFormAction);

$documentCount = isset($response) ? $response->getTotalResults() : 0;
if ($documentCount):
    $itemSetsCount = $response->getResourceTotalResults('item_sets');
    $itemsCount = $response->getResourceTotalResults('items');
    $displayParts = $searchPage->setting('display', []);
    $displayPartsHeader = array_filter($displayParts, function ($v) { return in_array($v, ['header', 'both']); });
    $displayPartsFooter = array_filter($displayParts, function ($v) { return in_array($v, ['footer', 'both']); });
endif;

$themeFunctions->appendVarToView('mainClass', 'resources-list-and-filters');

$isBrowse = $query->isBrowse();

$ariane = '<nav class="breadcrumbs content-with-margin">
    <ul>
        <li><a href="' . $url('site', ['site-slug' => $site->slug()]) . '">' . $escape($translate('Accueil')) . '</a></li>
        <li><span>' . $translate($isBrowse ? 'Consulter un document' : 'Résultats de recherche') . '</span></li>
    </ul>
</nav>';
$themeFunctions->appendVarToView('ariane', $ariane);
?>

<?php /* // Le formulaire de recherche principal est dans l'entête.
<?= $this->searchForm($searchPage, null, $skipFormAction) // Le formulaire de recherche principal est dans l'entête. ?>
*/ ?>

<?php if (!isset($response)): ?>

<aside class="search-facets">
    <div class="resources-list-filters-and-toggle toggle-parent">
    </div>
</aside>

<div class="search-results-wrapper content">
    <a class="resources-list-toggle-filters" href=""><?= $translate('Filtres') ?></a>
    <?= $this->pageTitle($itemSet ? $itemSet->displayTitle() : $translate($isBrowse ? 'Documents' : 'Résultats de recherche'), 1) ?>
    <p class="search-results-details noresults"><?= $translate('An error occured and your query returned no results.') ?></p>
</div>

<?php else: ?>

<?= $partial('search/facets', [
    'site' => $site,
    'searchPage' => $searchPage,
    'query' => $query,
    'response' => $response,
    'itemSet' => $itemSet,
]) ?>

<div class="search-results-wrapper content">

    <a class="resources-list-toggle-filters" href=""><?= $translate('Filtres') ?></a>

    <?php if ($itemSet): ?>

        <?php
        $vars->offsetSet('itemSet', $itemSet);
        $vars->offsetSet('resourceType', 'item_sets'); // TODO Check if really needed.
        $this->htmlElement('body')->appendAttribute('class', 'search-page item-set resource browse');
        ?>
    <?= $this->pageTitle($itemSet->displayTitle(), 1) ?>
    <div class="metadata">
        <?= $itemSet->displayValues() ?>
    </div>
    <div class="item-set-items">
        <h2><?= $translate('Documents') ?></h2>
    </div>

    <?php else: ?>

        <?php $this->htmlElement('body')->appendAttribute('class', 'search-page resource browse'); ?>
    <?= $this->pageTitle($translate($isBrowse
        ? 'Documents'
        : 'Résultats de recherche')) ?>

    <?php endif; ?>

    <?php if ($documentCount): ?>

        <?php if ($displayPartsHeader): ?>
        <?= $partial('search/results-header-footer', [
            'site' => $site,
            'searchPage' => $searchPage,
            'query' => $query,
            'response' => $response,
            'itemSet' => $itemSet,
            'resultPart' => 'header',
            'documentCount' => $documentCount,
        ]) ?>
        <?php endif; ?>

        <?php if ($itemSetsCount): ?>
        <?= $partial('search/resource-list', [
            'site' => $site,
            'searchPage' => $searchPage,
            'query' => $query,
            'response' => $response,
            'title' => sprintf($translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
            'resourceName' => 'item_sets',
        ]) ?>
        <?php endif; ?>

        <?php if ($itemsCount): ?>
        <?= $partial('search/resource-list', [
            'site' => $site,
            'searchPage' => $searchPage,
            'query' => $query,
            'response' => $response,
            'title' => sprintf($translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
            'resourceName' => 'items',
        ]) ?>
        <?php endif; ?>

        <?php if ($displayPartsFooter): ?>
            <?= $partial('search/results-header-footer', [
                'site' => $site,
                'searchPage' => $searchPage,
                'query' => $query,
                'response' => $response,
                'itemSet' => $itemSet,
                'resultPart' => 'footer',
                'documentCount' => $documentCount,
            ]) ?>
        <?php endif; ?>

    <?php else: ?>

        <ul class="noresults resources-list-tools">
            <li>
                <?php if (empty($query) && !$itemSet): ?>
                <?= $translate('Fill a query and get results.') ?>
                <?php elseif (empty($query) && $itemSet): ?>
                <?= $translate('This item set has no items.') ?>
                <?php else: ?>
                    <?php if (in_array($searchPage->subSetting('display', 'search_filters', 'header'), ['header', 'both'])): ?>
                <div class="search-results-part search-results-header">
                    <?= $this->searchingFilters($searchPage, $query, ['template' => 'common/search-filters-links']) ?>
                </div>
                    <?php endif; ?>
                <?= $translate('Your query returned no results') ?>
                <?php endif; ?>
            </li>
        </ul>

    <?php endif; ?>

</div>

<?php endif; ?>
