<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Form\MainSearchForm $form
 */

// Le formulaire est ajouté si le formulaire principal est un formulaire avancé.

// TODO Ajouter le même formulaire pour la recherche standard avancée (cf. common/advanced-search-form).

// TODO Inclures les attributs dans la configuration du formulaire, pas dans le code du thème.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
// $themeFunctions = $plugins->get('ThemeFunctions');

$formButton = $plugins->get('formButton');

// $site = $themeFunctions->currentSite();

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();

$form->setAttribute('class', trim($form->getAttribute('class') . ' form-search advanced-search-form'));

// TODO Vérifier si tout cela est toujours utile.
$elementReset = null;
$elementSubmit = null;
// Ne pas faire `foreach ($form as $name => $element)`, cela ne comprend pas le submit.
foreach ($form->getElements() as $element) switch ($element->getName()) {
    case 'q':
        $element
            ->setAttribute('class', trim($element->getAttribute('class') . ' advanced-search-text-input'));
        break;
    case 'form-reset':
        $element
            // The reset button is not used to clear this form.
            ->setAttribute('class', 'form-button clear-button form-search')
            ->setAttribute('form', $form->getAttribute('id'));
        $elementReset = $element;
        $form->remove($element->getName());
        break;
    case 'submit':
    case 'form-submit':
        $element
            // ->setLabel('Rechercher')
            ->setAttribute('class', 'form-button submit-button form-search')
            ->setAttribute('form', $form->getAttribute('id'));
        $elementSubmit = $element;
        $form->remove($element->getName());
        break;
    case 'item_set':
    case 'item_set_id':
    case 'item_set_id_is':
        $element
            ->setLabel('Rechercher par collection')
            ->setOption('empty_option', '')
            ->setOption('prepend_value_options', ['' => 'Toutes les collections'])
            ->setAttribute('data-placeholder', $translate('Choisir les collections'));
        break;
    case 'class':
    case 'resource_class':
    case 'resource_class_id':
    case 'resource_class_id_is':
        // value_options de resourceClass ne sont pas modifiables.
        // Les valeurs ajoutées vides ne servent pas avec chosen-select.
        // Le formulaire ne doit pas avoir été préparé (headroom?).
        $element
            ->setLabel('Rechercher par type de document')
            ->setOption('empty_option', '')
            ->setOption('prepend_value_options', ['' => 'Tous les types de document'])
            ->setAttribute('data-placeholder', $translate('Choisir les types de document'));
        break;
    case 'template':
    case 'resource_template':
    case 'resource_template_id':
    case 'resource_template_id_is':
        $element
            ->setLabel('Rechercher par type de ressource')
            ->setOption('empty_option', '')
            ->setOption('prepend_value_options', ['' => 'Tous les types de ressource'])
            ->setAttribute('data-placeholder', $translate('Choisir les types de ressource'));
        break;
    default:
        break;
}

// Prépare les labels et attributs spécifiques au thème.
$form
    ->setAttribute('class', trim($form->getAttribute('class') . ' advanced-search-form'))
    ->prepare();
?>

<dialog id="advanced-search-popup" class="advanced-search-popup">
    <div class="popup-scroll-content">
        <div class="advanced-search-popup-content">
            <div class="advanced-search-close close-popup-btn">
                <a href="#"></a>
            </div>
            <div class="advanced-search-form-parent">
                <h1><?= $translate('Recherche avancée') ?></h1>
                <?php if ($elementReset || $elementSubmit): ?>
                <ul class="form-buttons">
                    <?php if ($elementReset): ?>
                    <li><?= $formButton($elementReset) ?></li>
	                <?php endif; ?>
                    <?php if ($elementSubmit): ?>
                    <li><?= $formButton($elementSubmit) ?></li>
                    <?php endif; ?>
                </ul>
                <?php endif; ?>
                <?= $this->form($form) ?>
            </div>
        </div>
    </div>
</dialog>
