<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Query $query
 * @var \Laminas\Form\Element\Select $select
 * @var array $params
 */

if (count($select->getValueOptions()) <= 1) return;
?>

<div class="search-sort<?= empty($params['as_url']) ? '' : ' as-url search-sort-urls' ?> select-parent sort-list-select">
    <?php /*
    <?= $select->getlabel() ? $this->formLabel($select) : '' ?>
    */ ?>
    <?= $this->formSelect($select) ?>
</div>
