<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $mainColor
 * @var string $accentColor
 *
 * @todo Trouver un moyen de faire un fichier css dynamique plutôt que de le charger dans la page.
 */
?>

<?php if (strtoupper($mainColor) !== '#BA0000'): ?>
/* DESKTOP DANTE */
@media screen {
    .header-bottom {
        background-color: <?= $mainColor ?>;
    }
    a.logo-header {
        color:<?= $mainColor ?>;
    }
    .c-hamburger span {
        background: <?= $mainColor ?>;
    }
    .c-hamburger span::before,
    .c-hamburger span::after {
        background: <?= $mainColor ?>;
    }
    main aside p.aside-download-link {
        border-top: solid 1px <?= $mainColor ?>;
        border-bottom: solid 1px <?= $mainColor ?>;
    }
    main .content h1 {
        color: <?= $mainColor ?>;
    }
    main.item-content .content h1 {
        color: <?= $mainColor ?>;
    }
    main.depot-content .content h2 {
        color: <?= $mainColor ?>;
    }
    main.depot-content .content > form div.form-content.document-parts-forms > div.document-part-fields > div,
    main.depot-content .content > form div.form-content:not(:last-child),
    main.depot-content .content h2 {
        border-bottom: 1px solid <?= $mainColor ?>;
    }
    ul.resources-list .document-index {
        color: <?= $mainColor ?>;
    }
    ul.resources-list .document-details {
        border-bottom: solid 1px <?= $mainColor ?>;
    }
    .resources-pagination form input:focus {
        border: 1px solid <?= $mainColor ?>;
    }
    .advanced-search-popup h1 {
        color: <?= $mainColor ?>;
    }
    .limited-access-form-parent h1 {
        color: <?= $mainColor ?>;
    }
    .item-content-header {
        border-bottom: 3px solid <?= $mainColor ?>;
    }
    .open-science-content-header h1,
    .aside-page-header h1 {
        color: <?= $mainColor ?>;
    }
    main .content .page-block h1 {
        color: <?= $mainColor ?>;
    }
    .login main .content > .page-block:last-child {
        border-top: 1px solid <?= $mainColor ?>;
        border-bottom: 1px solid <?= $mainColor ?>;
    }
}
/* Menu Mobile */
@media screen and (max-width: 740px) {
    header {
        border-bottom: 4px solid <?= $mainColor ?>;
    }
    .header-bottom {
        background-color: <?= $mainColor ?>;
    }
}
<?php endif; ?>

<?php if (strtoupper($accentColor) !== '#BA0000'): ?>
a:link,
a:visited {
    color: <?= $accentColor ?>;
}
a:active,
a:hover {
    color: <?= $accentColor ?>;
    opacity: .75;
}
<?php endif; ?>
