<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $mainColor
 * @var string $accentColor
 *
 * @todo Trouver un moyen de faire un fichier css dynamique plutôt que de le charger dans la page.
 */
?>

<?php if (strtoupper($mainColor) !== '#EA3535' || strtoupper($accentColor) !== '#BA0000'): ?>
html {
    --primary-color: <?= $mainColor ?>;
    --primary-link-color: <?= $accentColor ?>;
}
<?php endif; ?>

<?php if (strtoupper($accentColor) !== '#BA0000' && strtoupper($accentColor) !== '#EA3535'): ?>
a:link,
a:visited {
    color: <?= $accentColor ?>;
}
a:active,
a:hover {
    color: <?= $accentColor ?>;
    opacity: .75;
}
<?php endif; ?>
